name: Build and Release

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - 'mappings/**'
  workflow_dispatch:
    inputs:
      norelease:
        description: "Don't release the build"
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup and Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Release to Maven
        if: |
          !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
        run: ./gradlew publish --stacktrace
